export { Home } from "./Home";
//export { AddDoctor } from "./AddDoctor";
export { Consultant } from "./Consultant";
export { Speacility } from "./Speacility";
export { Cardiolist } from "./Cardiolist";
export { ConsultantDetails } from "./ConsultantDetails";
export { Appoinment } from "./Appoinment";
export { MoreScreen } from "./MoreScreen";
export { AppoinmentsDetail } from "./AppoinmentsDetail";
export { BookAppointment } from "./BookAppointment";
export { PaymentDetail } from "./PaymentDetail";
export { InvoicesProfile } from "./InvoicesProfile";
export { ProfitLossStatement } from './ProfitLossStatement'
export { Slot } from "./Slot";
export { Slot2 } from "./Slot2";
